############################################################
# k apply -f k8s.e2e-sakuli-tests.yml -n OverrideMeWithK8SNamespace
# k port-forward e2e-sakuli-tests 6901:6901 -n OverrideMeWithK8SNamespace
# k delete -f k8s.e2e-sakuli-tests.yml -n OverrideMeWithK8SNamespace
############################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-script
data:
  checkout.sh: |-
    #!/bin/sh
    set -e
    git init .
    echo "git repository has been initialized:"
    echo "$(ls -ahl .git)"
    git remote add origin "${CHECKOUT_STEP_REPOSITORY}"
    echo "${CHECKOUT_STEP_REPOSITORY} has been added:"
    echo "$(git remote -v)"
    git fetch origin
    git reset --hard "${CHECKOUT_STEP_COMMIT}"
    echo "HEAD has been reset to ${CHECKOUT_STEP_COMMIT}"
    if [[ -z "$(ls)" ]]; then
      echo "empty directory. most probably git failed to fetch ${CHECKOUT_STEP_REPOSITORY}"
      exit 1
    fi
    chmod -R a+rw .
    echo "RW permissions have been set"
    echo "commit info:"
    echo "$(git log -n 1)"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: run-e2e-tests-script
data:
  run-e2e-tests.sh: |-
    #!/usr/bin/env bash
    cd /code/packages/e2e
    echo commit info:
    echo "$(git log -n 1)"
    echo node version:
    echo "$(node --version)"
    echo npm version:
    echo "$(npm --version)"
    npm ci --production
    cd e2e-suite
    sleep 20
    npx sakuli run .
    tail -f /dev/null
---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-sakuli-tests
spec:
  restartPolicy: Never
  initContainers:
    - name: git-checkout
      image: alpine/git
      command:
        - /root/bin/checkout.sh
      volumeMounts:
        - mountPath: /git
          name: repository
        - mountPath: /root/bin
          name: checkout-script
          readOnly: true
      env:
        - name: CHECKOUT_STEP_REPOSITORY
          value: "https://github.com/progaddict/sakuli.git"
        - name: CHECKOUT_STEP_COMMIT
          value: "339e360786342e1171a71dd113641665a0fbe0bc"
  containers:
    - name: e2e-sakuli-tests
      image: "OverrideMeWithAwsAccountNumber.dkr.ecr.eu-west-1.amazonaws.com/OverrideMeWithRegistryEndpointName/sakuli:2.3.0"
      args:
        - /tmp/scripts/run-e2e-tests.sh
      volumeMounts:
        - mountPath: /code
          name: repository
        - mountPath: /tmp/scripts
          name: run-e2e-tests-script
          readOnly: true
      env:
        - name: SAKULI_LICENSE_KEY
          value: "OverrideMeWithSakuliLicenseKey"
  volumes:
    - name: repository
      emptyDir: {}
    - name: checkout-script
      configMap:
        name: checkout-script
        defaultMode: 0555
    - name: run-e2e-tests-script
      configMap:
        name: run-e2e-tests-script
        defaultMode: 0555
