apiVersion: v1
kind: ConfigMap
metadata:
  name: run-e2e-tests-script
data:
  run-e2e-tests.sh: |-
    #!/usr/bin/env bash
    rm -rf /tmp/code
    mkdir -p /tmp/code
    cd /tmp/code
    git clone "${CHECKOUT_STEP_REPOSITORY}"
    cd sakuli
    git reset --hard "${CHECKOUT_STEP_COMMIT}"
    cd packages/e2e
    echo commit info:
    echo "$(git log -n 1)"
    echo node version:
    echo "$(node --version)"
    echo npm version:
    echo "$(npm --version)"
    npm ci --production
    cd e2e-suite
    sleep 20
    npx sakuli run .
    tail -f /dev/null
---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-sakuli-tests
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: e2e-sakuli-tests
      image: "OverrideMeWithAwsAccountNumber.dkr.ecr.eu-west-1.amazonaws.com/OverrideMeWithRegistryEndpointName/sakuli:2.3.0"
      imagePullPolicy: Always
      args:
        - /tmp/scripts/run-e2e-tests.sh
      volumeMounts:
        - mountPath: /tmp/scripts
          name: run-e2e-tests-script
          readOnly: true
      env:
        - name: CHECKOUT_STEP_REPOSITORY
          value: "https://github.com/progaddict/sakuli.git"
        - name: CHECKOUT_STEP_COMMIT
          value: "339e360786342e1171a71dd113641665a0fbe0bc"
        - name: SAKULI_LICENSE_KEY
          value: "OverrideMeWithSakuliLicenseKey"
  volumes:
    - name: run-e2e-tests-script
      configMap:
        name: run-e2e-tests-script
        defaultMode: 0555
